apiVersion: apps/v1
kind: Deployment
metadata:
  name: review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
        - name: review
          image: <AWS ID Number>.dkr.ecr.ap-northeast-2.amazonaws.com/review:1.0
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: MANAGEMENT_HEALTH_RABBIT_ENABLED
              value: "false"
            - name: SPRING_CLOUD_STREAM_DEFAULTBINDER
              value: "kafka"
            - name: SPRING_CLOUD_STREAM_BINDINGS_INPUT_CONSUMER_PARTITIONED
              value: "true"
            - name: SPRING_CLOUD_STREAM_BINDINGS_INPUT_CONSUMER_INSTANCECOUNT
              value: '2'
            - name: SPRING_CLOUD_STREAM_BINDINGS_INPUT_CONSUMER_INSTANCEINDEX
              value: '0'
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  name: review
spec:
  selector:
    app: review
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
