apiVersion: v1
kind: Service
metadata:
  name: spring-boot-grpc-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 18080
      targetPort: 18080
    - name: grpc
      port: 18888
      targetPort: 18888
  selector:
    app: spring-boot-grpc-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-grpc-server
  template:
    metadata:
      labels:
        app: spring-boot-grpc-server
    spec:
      containers:
        - name: spring-boot-grpc-server
          image: <AWS ID Number>.dkr.ecr.ap-northeast-2.amazonaws.com/grpc-server:1.0
          imagePullPolicy: Always
          tty: true
          ports:
            - name: http
              protocol: TCP
              containerPort: 18080
            - name: grpc
              protocol: TCP
              containerPort: 18888
