apiVersion: apps/v1
kind: Deployment
metadata:
  name: cqrs-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cqrs-query
  template:
    metadata:
      labels:
        app: cqrs-query
    spec:
      containers:
        - name: cqrs-query
          image: <AWS ID Number>.dkr.ecr.ap-northeast-2.amazonaws.com/cqrs-query:1.0
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_CLOUD_STREAM_DEFAULTBINDER
              value: "kafka"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cqrs-query
spec:
  selector:
    app: cqrs-query
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer